gameplan2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^scrum/', include('scrum.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'',include('scrum.urls')),
    url(r'users/', include('users.urls', namespace='users')),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    #redirect after login
    #url(r'^accounts/profile/$', TemplateView.as_view(template_name='scrum/portfolio.html'), name='home'),
]

scrum/urls.py
from django.conf.urls import url
#from . import views
from scrum.views.portfolioView import *
from scrum.views.portfolioView import PortfolioListbyStatus, PortfolioList, PortfolioDetails, PortfolioCreate, PortfolioUpdate, PortfolioDelete
from scrum.views.releaseView import ReleaseList, ReleaseCreate, ReleaseDetails, ReleaseDelete, ReleaseUpdate
from scrum.views.releaseView import UserstoryDetails, UserstoryCreate, UserstoryUpdate, UserstoryDelete
from scrum.views.releaseView import TaskCreate, TaskUpdate, TaskDelete
from scrum.views.releaseView import SprintDetails, SprintCreate, SprintUpdate, SprintDelete
from scrum.views.teamview import TeamList, TeamCreate, TeamUpdate, TeamDetails, TeamDelete
from scrum.views.teamview import TeamResourceCreate, TeamResourceUpdate, TeamResourceDelete
app_name = 'scrum'
urlpatterns = [
    url(r'^$',  PortfolioList.as_view(), name='index'),
    #url(r'^dashboard', Dashboard.as_view(), name='dashboard'),
    url(r'^portfolio/list/(?P<status_id>\d+)$',  PortfolioListbyStatus.as_view(), name='portfolioListbyStatus'),
    url(r'^portfolio/list', PortfolioList.as_view(), name='portfolioList'),
    url(r'^portfolio/(?P<pk>\d+)$', PortfolioDetails.as_view(), name='portfolio-detail'),
    url(r'^portfolio/add', PortfolioCreate.as_view(), name='portfolio-add'),
    url(r'^portfolio/update/(?P<pk>\d+)$', PortfolioUpdate.as_view(), name='portfolio-update'),
    url(r'^portfolio/delete/(?P<pk>\d+)$', PortfolioDelete.as_view(), name='portfolio-delete'),
    # release Release
    url(r'^releaseList',  ReleaseList.as_view(), name='releaseList'),
    url(r'^release/(?P<pk>\d+)$', ReleaseDetails.as_view(), name='release-detail'),
    url(r'^release/add/(?P<portfolio_id>\d+)$', ReleaseCreate.as_view(), name='release-add'),
    url(r'^release/update/(?P<pk>\d+)$', ReleaseUpdate.as_view(), name='release-update'),
    url(r'^release/delete/(?P<pk>\d+)$', ReleaseDelete.as_view(), name='release-delete'),
    # Userstory, userstory
    #url(r'^releaseList', ReleaseList.as_view(), name='releaseList'),
    url(r'^Userstory/(?P<pk>\d+)$', UserstoryDetails.as_view(), name='userstory-detail'),
    url(r'^Userstory/add/(?P<release_id>\d+)$',UserstoryCreate.as_view(), name='userstory-add'),
    url(r'^Userstory/update/(?P<pk>\d+)$',UserstoryUpdate.as_view(), name='userstory-update'),
    url(r'^Userstory/delete/(?P<pk>\d+)$', UserstoryDelete.as_view(), name='userstory-delete'),

    # Task, task
    #url(r'^Task/(?P<pk>\d+)$', TaskDetails.as_view(), name='userstory-detail'),
    url(r'^Task/add/(?P<userstory_id>\d+)$', TaskCreate.as_view(), name='task-add'),
    url(r'^Task/update/(?P<pk>\d+)$', TaskUpdate.as_view(), name='task-update'),
    url(r'^Task/delete/(?P<pk>\d+)$', TaskDelete.as_view(), name='task-delete'),
    # Sprint, sprint
    # release Release
    # not needed now may be later:
    # url(r'^sprintList', SprintList.as_view(), name='releaseList'),
    # not needed now may be later:
    url(r'^sprint/(?P<pk>\d+)$', SprintDetails.as_view(), name='sprint-detail'),
    url(r'^sprint/add/(?P<release_id>\d+)$', SprintCreate.as_view(), name='sprint-add'),
    url(r'^sprint/update/(?P<pk>\d+)$', SprintUpdate.as_view(), name='sprint-update'),
    url(r'^sprint/delete/(?P<pk>\d+)$', SprintDelete.as_view(), name='sprint-delete'),
    #url(r'^sprint/userstory-select/(?P<pk>\d+)$', Sprint_userstorySelect.as_view(), name='sprint-userstory-select'),
    # url(r'^portfolio/Details/(?P<id>\d+)/$', portfolioDetails(), name='portfolioDetails'),
   # url(r'^portfolio/Update/(?P<id>\d+)/$', portfolios.portfolioUpdate, name='portfolioUpdate'),
   # url(r'^portfolio/Update', portfolios.portfolioUpdate, name='portfolioUpdate'),
   # url(r'^portfolio/new$', portfolios.new_portfolio, name='new_portfolio'),
   # url(r'^portfolio', portfolios.portfolio, name='portfolio'),
   # url(r'^userstoryList', userstories.,
    #url(r'^release/(?P<id>\d+)/$', portfolios.releaseUpdate, name='releaseUpdate'),
   # url(r'^release/new$', userstories.new_userstory, name='new_release'),
   # url(r'^userstory/new$', userstories.new_userstory, name='new_userstory'),
    #url(r'^sprint/new$', views.new_sprint, name='new_sprint'),
    #url(r'^task/new$', views.new_task, name='new_task'),
    #url(r'^team/new$', views.new_team, name='new_release'),

    # Team, team
    url(r'^team/list', TeamList.as_view(), name='team-list'),
    url(r'^team/(?P<pk>\d+)$', TeamDetails.as_view(), name='team-detail'),
    url(r'^team/add', TeamCreate.as_view(), name='team-add'),
    url(r'^team/update/(?P<pk>\d+)$', TeamUpdate.as_view(), name='team-update'),
    url(r'^team/delete/(?P<pk>\d+)$', TeamDelete.as_view(), name='team-delete'),
    url(r'^teamresource/add', TeamResourceCreate.as_view(), name='teamresource-add'),
    url(r'^teamresource/update/(?P<pk>[\w\-]+)$', TeamResourceUpdate.as_view(), name='teamresource-update'),
    url(r'^teamresource/delete/(?P<pk>[\w\-]+)$', TeamResourceDelete.as_view(), name='teamresource-delete'),
]

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Dictionary(models.Model):
    key = models.CharField(db_column='Key', primary_key=True, max_length=100)  # Field name made lowercase.
    shorttitle = models.CharField(db_column='shortTitle', max_length=100, blank=True, null=True)  # Field name made lowercase.
    longtitle = models.CharField(db_column='LongTitle', max_length=100, blank=True, null=True)  # Field name made lowercase.
    contexthelp = models.CharField(db_column='ContextHelp', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'dictionary'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Externallinks(models.Model):
    externallinksid = models.AutoField(db_column='externalLInksid', primary_key=True)  # Field name made lowercase.
    url = models.CharField(max_length=100, blank=True, null=True)
    taskid = models.ForeignKey('Task', models.DO_NOTHING, db_column='taskid')
    linkslabelid = models.ForeignKey('Tasklinkslabel', models.DO_NOTHING, db_column='linksLabelid')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'externallinks'


class Portfolilables(models.Model):
    portfolilablesid = models.AutoField(db_column='portFoliLablesid', primary_key=True)  # Field name made lowercase.
    label = models.CharField(max_length=100, blank=True, null=True)
    portfolioid = models.ForeignKey('Portfolio', models.DO_NOTHING, db_column='portfolioid')

    class Meta:
        managed = False
        db_table = 'portfolilables'


class Portfolilinkslabel(models.Model):
    portfolilinkslabelid = models.AutoField(db_column='portFoliLinksLabelid', primary_key=True)  # Field name made lowercase.
    label = models.CharField(max_length=100, blank=True, null=True)
    url = models.CharField(db_column='Url', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'portfolilinkslabel'


class Portfolio(models.Model):
    portfolioid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    portfoliotypeid = models.ForeignKey('Portfoliotype', models.DO_NOTHING, db_column='portfolioTypeid')  # Field name made lowercase.
    details = models.TextField(blank=True, null=True)
    rank = models.BigIntegerField()
    portfoliostatusid = models.ForeignKey('Portfoliostatus', models.DO_NOTHING, db_column='portfoliostatusid')
    owner = models.ForeignKey('Resource', models.DO_NOTHING, db_column='owner')

    class Meta:
        managed = False
        db_table = 'portfolio'
        unique_together = (('portfolioid', 'owner'),)


class Portfoliolinks(models.Model):
    portfolilinksid = models.AutoField(db_column='portFoliLinksid', primary_key=True)  # Field name made lowercase.
    portfolioid = models.ForeignKey(Portfolio, models.DO_NOTHING, db_column='portfolioid')
    portfolilinkslabelid = models.ForeignKey(Portfolilinkslabel, models.DO_NOTHING, db_column='portFoliLinksLabelid')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'portfoliolinks'


class Portfolioreleases(models.Model):
    portfolioid = models.IntegerField()
    releaseid = models.AutoField(db_column='releaseid', primary_key=True)  # Field name made lowercase.
    planstartdate = models.DateField(db_column='planStartDate', blank=True, null=True)  # Field name made lowercase.
    actualstartdate = models.DateField(db_column='actualStartDate', blank=True, null=True)  # Field name made lowercase.
    teamid = models.ForeignKey('Team', models.DO_NOTHING, db_column='teamid')
    planenddate = models.DateField(db_column='planEndDate', blank=True, null=True)  # Field name made lowercase.
    actualenddate = models.DateField(db_column='actualEndDate', blank=True, null=True)  # Field name made lowercase.
    details = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'portfolioreleases'


class Portfoliostatus(models.Model):
    portfoliostatusid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'portfoliostatus'


class Portfoliotype(models.Model):
    portfoliotypeid = models.AutoField(db_column='portfolioTypeid', primary_key=True)  # Field name made lowercase.
    title = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'portfoliotype'


class Progressratio(models.Model):
    progressratioid = models.AutoField(db_column='progressRatioid', primary_key=True)  # Field name made lowercase.
    descriptions = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'progressratio'


class Resource(models.Model):
    resourceid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    active = models.IntegerField()
    teamid = models.ForeignKey('Team', models.DO_NOTHING, db_column='teamid')
    resourcetypeid = models.ForeignKey('Resourcetype', models.DO_NOTHING, db_column='resourceTypeid')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'resource'


class Resourcetype(models.Model):
    resourcetypeid = models.AutoField(db_column='resourceTypeid', primary_key=True)  # Field name made lowercase.
    description = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'resourcetype'


class Sprint(models.Model):
    sprintid = models.AutoField(primary_key=True)
    details = models.CharField(max_length=100, blank=True, null=True)
    startdate = models.DateField(db_column='startDate', blank=True, null=True)  # Field name made lowercase.
    end = models.DateField(db_column='End', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'sprint'


class Task(models.Model):
    taskid = models.BigAutoField(primary_key=True)
    userstoryid = models.ForeignKey('Userstory', models.DO_NOTHING, db_column='userStoryid', blank=True, null=True)  # Field name made lowercase.

scrum/models.py
# coding=utf-8
from scrum.submodels.portfoliomodel import *
from scrum.submodels.teammodel import *
from scrum.submodels.portfolioReleasemodel import *

scrum/views/userstoriesView.py
from django.shortcuts import render, HttpResponse
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.http import Http404
from scrum.forms import UserstoryForm
from django.core.urlresolvers import reverse
from  scrum.models import PortfolioStatus, Portfolio, PortfolioReleases, Userstory
from django.views.generic import ListView, DetailView
from scrum.submodels.portfolioReleasemodel import Userstory

# unassigned
# release wise filter
# a user story must belogn to a release of a portfolio

@login_required
class userstoryList(ListView):
    template_name = 'scrum/userstory.html'
    context_object_name = 'userstory'

    def get_queryset(self):
        """Return the last five published questions."""
        #return Userstory.objects.order_by('-userstoryid')[:30]
        return Userstory.objects.order_by('-userstoryid')


@login_required
def new_userstory(request):
    if request.method != 'POST':
        form = UserstoryForm()
        context = {'form': form}
        return render(request, 'scrum/userstory_form.html', context)


def userstoryUpdate(request, id=-1):
    if request.method != 'POST':
        userstory = Userstory.objects.get(userstoryid=id)
        form = UserstoryForm(instance=userstory)
        context = {'userStory': userstory, 'form': form}
        return render(request, 'scrum/userstory_form.html', context)
    else:
        if id== -1:
            form = UserstoryForm(data=request.POST)
        else:
            # change in the form
            portfolio = UserStory.objects.get(portfolioid=id)
            form = UserstoryForm(instance=portfolio, data=request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse(('scrum:portfolio')))
        else:
            return HttpResponse("invalid form.")

scrum/templates/scrum/form_template.html
{%  for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}            </span>
            <label class="control-label col-sm-2">{{ field.label_tag }}</label>
            <div class="col-sm-10">{{ field }}</div>
        </div>
    </div>
{% endfor %}

scrum/templates/scrum/index.html
{% extends "scrum/header.html" %}
{% block content  %}
    <h1> wellcome to Gameplan 2</h1>
{% endblock content %}

scrum/templates/scrum/portfolioForm.html
{% extends "scrum/header.html" %}
{% block content %}
<form action="{% url 'scrum:portfolioUpdate' %}" method='post'>
    {% csrf_token %}
<div class="table-responsive" >
  <table class="table-striped table-bordered" table-hover width="60%" align="center">
      <tr>
      <td colspan="2" align="center">
          <button name="submit"> Portfolio Entry</button>
      </td>
  </tr>
    {{ form.as_table }}
  <tr>
      <td colspan="2" align="right">
          <button name="submit"> Save</button>
      </td>
  </tr>
  </table>
    <div>

    </div>
</div>


</form>
{% endblock content %}

scrum/templates/scrum/portfolio_list.html
{% extends "scrum/header.html" %}
{% block breadcrumbs %}
    {{ block.super }}
    <ul class="nav navbar-nav">
        <li><a href="{% url 'scrum:portfolioList' %}">Porfolios</a></li>
     </ul>

{% endblock %}

{% block sidebar %}
<ul class="sidebar-nav">
   {% if portfolio_status %}
        {% for status in portfolio_status %}
          <li><a href="{% url 'scrum:portfolioListbyStatus' status.portfoliostatusid %}">{{ status.title }}</a></li>
        {% endfor %}
    {% endif %}
</ul>
{% endblock %}
{% block content %}
<div class="container-fluid text-center">
    <div class="panel col-sm-6 col-lg-12 ">
        <div class="panel-body" style="background-color:#{{statusColor}};color:#FFFFFF">

            <div class="well">

                <a href="{% url 'scrum:portfolio-add' %}  ">add new entry</a></div>

            </div>
        </div>

      {% if portfoliolist %}
        {% for portfolio in portfoliolist %}
    <div class="panel col-sm-6 col-lg-3">
        <div class="panel-body" style="background-color:#{{statusColor}};color:#FFFFFF">

            <ul class="list-group ">
                <div align="right">
                    <a href="{% url 'scrum:portfolio-detail' portfolio.portfolioid %}">Details</a>
                </div>
                    <li class="list-group-item list-group-item-info"><strong>Title:</strong>
                    <span class="pull-right">{{portfolio.title}}</span>
                </li>
                    
                </li>
                <li class="list-group-item list-group-item-info"><strong>Type:</strong>
                    <span class="pull-right">{{portfolio.portfoliotypeid}}</span>
                </li>
                <li class="list-group-item list-group-item-warning"><strong>Onwer:</strong>
                    <span class="pull-right">{{portfolio.owner}}</span>
                </li>
                <li class="list-group-item list-group-item-danger"><strong>Project Duration:</strong>
                    <span class="pull-right">{{totalDays}} </span>
                </li>
            </ul>
              <div align="right">
                   <span class="pull-left"><a href="{% url 'scrum:portfolio-update' portfolio.portfolioid %}">Edit</a></span>
                     <span class="pull-right"><a href="{% url 'scrum:portfolio-delete' portfolio.portfolioid %}">Delete</a></span>
              </div >
        </div>
    </div>

     {% endfor %}
    {% else %}
      <div class="well">
        <p>No portfolio available.</p>
      </div>
    {% endif %}
 

</div>
</body>
</html>
{% endblock content %}

scrum/templates/scrum/releaseDetails.html
{% extends "scrum/header.html" %}

{% block sidebar %}
<ul class="sidebar-nav">
    {% if release_status %}
        {% for status in release_status %}
          <li><a href="#">{{ status.title }}</a></li>
        {% endfor %}
    {% endif %}
</ul>

{% endblock %}
{% block breadcrumbs %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'scrum:portfolioList' %}">Porfolios</a></li>
    <li><a href ="{% url 'scrum:portfolio-detail' release.portfolioid_id %} ">{{ release.portfolioid }}</a> </li>
    <li><a href="{{ PortfolioReleases.get_absolute_url }}"> Release</a> </li>
</ul>
{% endblock %}
{% block content %}
<div align="center" class="panel panel-primary col-lg-12" style="padding: 10px;" border="1">
    <table class="table table-hover">
        <tr>
            <td class="warning">Release</td><td >{{ release.portfolioid}} {{ release.details }}</td>

            <td class="warning">Expected Start</td><td >{{ release.planstartdate }}</td>
            <td class="info">Actual start</td><td >{{ release.actualstartdate }}</td>
        </tr>

        <tr >
            <td class="info">Current Status</td><td >{{ release.releasestatusid}}</td>
            <td class="warning">Expected End</td><td >{{ release.planenddate }}</td>
            <td class="info">Actual End</td><td >{{ release.actualenddate }}</td>
        </tr>

    </table>
</div>
<div class="panel panel-primary col-lg-6" style="margin-left:20px;margin-top:20px" border="1">
    <table class="table table-striped table-bordered table-condensed">
        <thead>

            <tr>
                <td colspan="5" class="btn btn-info" role="button"><a href = "{% url 'scrum:userstory-add' release.releaseid %}"> Add New Userstory </a></td>
            </tr>
        </thead>
        <thead>
            <tr>
                <th> User Stories </th>
                <th> Added into</th>
                <th>  </th>
                <th>  </th>
                <th> Update Log </th>
            </tr>
        </thead>
    {% for userstory in release.userstory_set.all %}

        <tr>
            <td><a href = "{% url 'scrum:userstory-detail' userstory.userstoryid %}"> {{userstory.userstoryid}}{{ " - " }}{{  userstory.details }}</a></td>
            <td>{% if userstory.sprintid_id %}
                    {{userstory.sprintid_id}}{{ " - " }}{{  userstory.sprintid }}
                {% else %}
                    {{ 'None' }}
                {%  endif %}</td>
            <td align="center">    <a href="{% url 'scrum:userstory-update' userstory.userstoryid %}">Edit</a></td>
            <td align ="center">    <a href="{% url 'scrum:userstory-delete' userstory.userstoryid %}">delete</a></td>
            <td>created {{ userstory.createdate }} by {{ userstory.createby }} last updated {{ userstory.updatedate }} by {{ userstory.updateby }} </td>
        </tr>
    {% endfor %}
   </table>
</div>
<div class="panel panel-primary col-lg-5" style="margin-left:20px;margin-top:20px" border="1">
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <td colspan="4" class="btn btn-info" role="button"><a href = "{% url 'scrum:sprint-add' release.releaseid %}"> Add New Sprint </a></td>
            </tr>
        </thead>
    {% for sprint in release.sprint_set.all %}

        <tr>
            <td><a href = "{% url 'scrum:sprint-detail' sprint.sprintid %}"> {{sprint.sprintid}}{{ " - " }}{{  sprint.details }}</a></td>
            <td align="center">    <a href="{% url 'scrum:sprint-update' sprint.sprintid %}">Edit</a></td>
            <td align ="center">    <a href="{% url 'scrum:sprint-delete' sprint.sprintid %}">delete</a></td>
            <td>started on  {{ sprint.startdate }} by {{ sprint.createby }} last updated {{ sprint.updatedate }} by {{ sprint.updateby }} </td>
        </tr>
    {% endfor %}
   </table>
</div>
{% endblock %}

scrum/templates/scrum/userstoryDetails.html
{% extends "scrum/header.html" %}

{% block breadcrumbs %}
    {{ block.super }}
    <ul class="nav navbar-nav">
      <li><a href="{% url 'scrum:portfolioList' %}">Porfolios</a></li>
      <li><a href="{%  url 'scrum:releaseList' %}">{{ 'Release' }}</a></li>
      <li><a href="{{ userstory.get_absolute_url }}">{{ userstory.title }}</a></li>
    </ul>
{% endblock %}
{% block sidebar %}

<div>

</div>
{% endblock %}
{% block content %}
<div align="center" class="panel panel-primary col-lg-12" style="padding: 10px;" border="1">
    <table class="table table-hover">
        <tr>
            <td class="warning">User Story </td><td > {{ userstory.title }}</td>

            <td class="warning">Sprint</td><td >{{ userstory.sprintid}}</td>
        </tr>

        <tr >
            <td class="info">Owner</td><td >{{ userstory.createby }}</td>
            <td class="info">Current Status</td><td >{{ userstory.userstorystatusid }}</td>
        </tr>
    </table>
</div>
<br />

<div class="panel panel-primary col-lg-12" style="margin-left:20px;margin-top:20px" border="1">
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <td colspan="5" class="btn btn-info" role="button"><a href = "{% url 'scrum:task-add' userstory.userstoryid %}"> Add New Task </a></td>
            </tr>
        </thead>
        <thead>
            <tr>
                <th> Task  </th>
                <th> Estimated Start</th>
                <th> Actual Start </th>
                <th> Estimated Duration </th>
                <th> Actual Duration </th>
            </tr>
        </thead>
    {% for task in userstory.task_set.all %}

        <tr>
            <td><a href = "{% url 'scrum:task-update' task.taskid %}"> {{task.taskid}}{{ " - " }}{{  task.details }}</a></td>
             <td align="center">    <a href="{% url 'scrum:task-update' task.taskid %}">Edit</a></td>
            <td align ="center">    <a href="{% url 'scrum:task-delete' task.taskid %}">delete</a></td>
            <td>est. Start {{ task.estmatedstart }} actual {{ task.actualstart }} assigned to {{ task.resourceid }} </td>
        </tr>
    {% endfor %}
   </table>
</div>
{% endblock %}